name: Release Please

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      releaseAs:
        description: 'Release as version'
        required: true
        type: string

permissions:
  contents: write
  id-token: write
  packages: write
  pull-requests: write

jobs:
  release-please:
    uses: voxpelli/ghatemplates/.github/workflows/release-please.yml@main
    secrets: inherit
    with:
      releaseAs: ${{ inputs.releaseAs }}
      packageName: "connect-pg-simple"
      bootstrapSha: 83abd0081f6d6a43e1e00cb57d97ec00d04b7a82
